# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 996c1b522c7c0ec3d22b93337be208fb3c1cf79112e538a46b3c6d2eaa66c3abbd3f60d8bc894572370f7e2cf3e56d34dfb763e207c2d7684a372f9fc0037515

test:
  secret_key_base: 0b770cc44ceada929cf1ca7775f0af793de7b0f4c537934798a8f902b33953073b1867cc93443834eb10684c41971229f9665464aa8aadd0143aa07be05c9b6f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
